# Generated by Django 6.0.1 on 2026-01-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rent', '0003_alter_tenant_property_alter_tenant_rent_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
            preserve_default=False,
        ),
    ]
