# Generated by Django 6.0.1 on 2026-01-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rent', '0004_property_price_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
