# Generated by Django 6.0.1 on 2026-01-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rent', '0006_propertyapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(default='M-Pesa', max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smart_rent.utilitybill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_rent.tenant')),
            ],
        ),
    ]
