# Generated by Django 6.0.1 on 2026-01-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rent', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(default='Middle Class', max_length=50),
        ),
    ]
