# Generated by Django 6.0.1 on 2026-01-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rent', '0008_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, default='default_house.jpg', null=True, upload_to='property_pics/'),
        ),
    ]
