# Generated by Django 6.0.1 on 2026-01-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rent', '0009_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('1-Bedroom Apartment', '1-Bedroom Apartment'), ('2-Bedroom Apartment', '2-Bedroom Apartment'), ('3-Bedroom Apartment', '3-Bedroom Apartment'), ('Executive/Serviced Apartment', 'Executive/Serviced Apartment'), ('Bungalow', 'Bungalow'), ('Maisonette', 'Maisonette'), ('Townhouse', 'Townhouse'), ('Villa', 'Villa'), ('Student Hostel/Housing', 'Student Hostel/Housing'), ('Airbnb/Short-Term Rental', 'Airbnb/Short-Term Rental')], default='2-Bedroom Apartment', max_length=100),
        ),
    ]
